# Generated by Django 2.2 on 2021-09-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='article/%Y/%m/%d/', verbose_name='标题图'),
        ),
    ]
