# Generated by Django 2.2 on 2021-10-12 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211013_0125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name': '类别管理', 'verbose_name_plural': '类别管理'},
        ),
        migrations.RemoveField(
            model_name='articlecategory',
            name='advertis',
        ),
        migrations.AlterModelTable(
            name='articlecategory',
            table='tb_category',
        ),
    ]
